name: Jordan Arscot
favicon: null
layout_spectrum: 0.76322
typography_spectrum: 0.60111
title: Welcome to the grid...
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0e0f11'
    - '#fffeff'
    - '#a9a286'
    - '#0f561a'
    - '#00acde'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
