typography_spectrum: 0.27458
color:
  brandColors:
    - '#d3d1ce'
    - '#040404'
    - '#777674'
    - '#00aeef'
    - '#006b9c'
  brandStrength: 0.75
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.75458
analytics:
  google: null
  facebook: null
  twitter: null
name: Empereol
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Welcome to the grid...
purpose: []
