name: Jordan Arscot
favicon: null
layout_spectrum: 0.75458
typography_spectrum: 0.35903
title: Welcome to the grid...
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d3d1ce'
    - '#040404'
    - '#777674'
    - '#00aeef'
    - '#006b9c'
  brandStrength: 0.75
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
