name: Jordan Arscot
favicon: null
layout_spectrum: 0.22659130534157157
typography_spectrum: 0.4618092307355255
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6670694211497903
  lightness: 0.47112716012634337
  saturation: 0.8724441782105714
  rhythmicContrast: 0.163947029504925
purpose: []
